# mostly traefik sample.
# only use different ports for entrypoints (http, https),
# the reason is because running as a non-priviledged user.
defaultEntryPoints = ["http", "https"]

# enable dashboard
[web]
address = ":8081"

# Entrypoints, http and https
[entryPoints]
  # http should be redirected to https
  [entryPoints.http]
  address = ":8080"
    [entryPoints.http.redirect]
    entryPoint = "https"

  # https is the default
  [entryPoints.https]
  address = ":8443"
    [entryPoints.https.tls]

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
email = "letsencrypt@example.com"
storage = "acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true
