kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-config
data:
  traefik.toml: |
    [web]
    address = ":8081"

    logLevel = "DEBUG"
    defaultEntryPoints = ["http", "https"]

    [kubernetes]

    [entryPoints]
      [entryPoints.http]
      address = ":8080"
      [entryPoints.https]
      address = ":8443"
        [entryPoints.https.tls]

    [acme]
    email = "test@traefik.io"
    storage = "acme.json"
    entryPoint = https
    onDemand = false
    OnHostRule = true
