kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-config
data:
  traefik.toml: |
    logLevel = "DEBUG"
    defaultEntryPoints = ["http", "https"]
    [kubernetes]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
    [acme]
    email = "letsencrypt@example.com"
    storage = "/etc/letsencrypt/acme.json"
    entryPoint = "https"
    onDemand = false
    OnHostRule = true
