kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-config
data:
  traefik.toml: |
    logLevel = "DEBUG"
    defaultEntryPoints = ["http", "https"]
    [entryPoints]
      [entryPoints.http]
      address = ":8080"
      [entryPoints.https]
      address = ":8443"
        [entryPoints.https.tls]

    [acme]
    email = "test@traefik.io"
    storage = "/acme/acme.json"
    entryPoint = "https"
    onDemand = true
    OnHostRule = true
    acmeLogging = true
    caServer = "https://acme-staging.api.letsencrypt.org/directory"

    [web]
    address = ":8081"
      [web.metrics.prometheus]
        Buckets=[0.1,0.3,1.2,5.0]
    
    [kubernetes]
