kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-config
data:
  traefik.toml: |
    [web]
    address = ":8081"
    logLevel = "DEBUG"
    defaultEntryPoints = ["http"]
    [kubernetes]
    [entryPoints]
      [entryPoints.http]
      address = ":8080"
